### ISSUE TITLE
Symbol resolution fails for system libraries in DevTools stack traces in Performance tab

### ISSUE THREAD

**Issue by pwasowski2** [flutter-tizen/engine#95]
The problem is described in: https://github.com/flutter-tizen/engine/issues/53#issuecomment-847459549

> run an app in profile mode and open the Performance view in Flutter DevTools, you will see this screen:
> 
> ![DevTools view](https://user-images.githubusercontent.com/40190588/119424620-c6744f80-bd40-11eb-85e6-3b8dab34b2b5.png)
> 
> As you can see in the stack traces at the bottom of the view (CPU Flame Chart), symbols are resolved to their offsets within the shared objects (/proc/self/fd/35/lib/libflutter_engine.so+0x.....) but not their actual names. I'm not sure whether this is normal (because the symbols were stripped out).

**Comment by bbrto21** [comment]
The inspiration from this conversation(https://github.com/flutter-tizen/engine/pull/97#issuecomment-849255272) has led to the following progress:

![Screenshot from 2021-05-27 12-06-48](https://user-images.githubusercontent.com/1579532/119761980-cbbfce80-bee7-11eb-9a86-ea2c5dd22715.png)

**Comment by bbrto21** [comment]
I checked the profile tool using three .so as follows
Among them, most symbols were resolved when using .so with the --unoptimized option.
@pwasowski2 Could you check it?

**profile**
![profile](https://user-images.githubusercontent.com/1579532/120130600-89590300-c201-11eb-8f69-4d39de795270.png)

**profile.so.unstripped**
![profile so unstripped](https://user-images.githubusercontent.com/1579532/120130679-bc9b9200-c201-11eb-852c-b743557923b0.png)

**profile_unopt**
![profile_unopt](https://user-images.githubusercontent.com/1579532/120130646-a42b7780-c201-11eb-9408-1cf1e09ed64d.png)
To use --unoptimized, you may need this
```
diff --git a/shell/platform/tizen/BUILD.gn b/shell/platform/tizen/BUILD.gn
index 809474371..550d19517 100644
--- a/shell/platform/tizen/BUILD.gn
+++ b/shell/platform/tizen/BUILD.gn
@@ -161,6 +161,7 @@ template("embedder_for_profile") {
     public_deps = [ ":flutter_engine" ]
 
     deps = [
+      "//flutter/runtime:libdart",
       "//flutter/shell/platform/common/cpp:common_cpp",
       "//flutter/shell/platform/common/cpp:common_cpp_input",
       "//flutter/shell/platform/common/cpp:common_cpp_library_headers",

```

**Comment by bbrto21** [comment]
As a result of test and trying based on several config options, I think it depends on ["//build/config:debug"](https://github.com/flutter/buildroot/blob/ff1975def53bfdaa1ff3f4b0cceabf54e1323392/build/config/BUILDCONFIG.gn#L373)

**Comment by pwasowski2** [comment]
@bbrto21, I think you've nailed it 👌 Thanks a lot 😃 

Native symbols indeed resolve after adding `--unoptimized` flag. Some of them (e.g. from libc.so) are still not resolved, but installing related `*-debug.rpm`s solves the problem and proper names are shown for them, too.

The question now is, what should we do about it? IMO, turning `--unoptimized` on by default for release binaries is not an option. Adding this flag makes binaries like `libflutter_tizen_mobile.so` orders of magnitude larger (15 MB vs 0.35 MB when I checked it) and probably has other side effects, that we wouldn't like to see in release binaries, too.

What about just adding information, that adding `--unoptimized` flag switches on the symbol resolution, to the wiki (I guess this will be the right place: https://github.com/flutter-tizen/flutter-tizen/wiki/Miscellaneous)? 

@bbrto21, @swift-kim what do you think about it?

**Comment by swift-kim** [comment]
> turning `--unoptimized` on by default for release binaries is not an option.

Agreed.

> and probably has other side effects,

Right. Turning on the unopt flag significantly lowers the performance as well. And that's why we can't use the "unoptimized" binaries for CPU profiling and performance analysis. So if we want to get correct results from the profiling tools, we need to find a way to fix the symbol resolution issue without disabling optimizations.

> What about just adding information, that adding `--unoptimized` flag switches on the symbol resolution, to the wiki

I think the best place would be the "Building the engine" page.

**Comment by bbrto21** [comment]
@pwasowski2 @swift-kim I agree too

**Comment by pwasowski2** [comment]
Ok, I'll go further down the rabbit hole and see how we can get all the symbols for profile builds ;)

I'll update the wiki afterwards.

**Comment by pwasowski2** [comment]
I have investigated the problem a little bit more and have found out a way of resolving more symbols on `profile` builds.

First, look at this change draft of `tools/gn `: https://github.com/pwasowski2/engine/commit/b9b44b9ad8b35f58c10e674be68282d42b73024d
Flutter devs have commented out `enable_profiling` flag from `gn` wrapper script. It means, that `enable_profiling` is always false and thus this conditional is not executed: https://github.com/flutter/buildroot/blob/ff1975def53bfdaa1ff3f4b0cceabf54e1323392/build/config/compiler/BUILD.gn#L346. 
(When `enable_profiling` is true, `-g` flag is added to cflags, which seems to be _the flag_ for turning symbols on).

After applying https://github.com/pwasowski2/engine/commit/b9b44b9ad8b35f58c10e674be68282d42b73024d# and running a build with the following set of `gn` flags (no `--unoptimized`):

```bash
flutter/tools/gn \
--target-os linux \
--linux-cpu arm \
--no-goma \
--target-toolchain `pwd`/tizen_tools/toolchains \
--target-sysroot `pwd`/tizen_tools/sysroot/arm \
--target-triple armv7l-tizen-linux-gnueabi \
--runtime-mode profile \
--enable-fontconfig \
--embedder-for-target \
--disable-desktop-embeddings \
--build-tizen-shell
```
we get more symbols in the profiler view.

**`enable_profiling = false`**
<img width="959" alt="linux_profile_arm_enable_profiling_commented_out" src="https://user-images.githubusercontent.com/38784511/120475384-96185b00-c3a9-11eb-837a-ea5a279aff6f.PNG">

**`enable_profiling = true`**
<img width="960" alt="linux_profile_arm_enable_profiling_uncommented" src="https://user-images.githubusercontent.com/38784511/120475395-99abe200-c3a9-11eb-8bad-4df7a89bbe9a.PNG">

As you can see, many more symbols are resolved, but some of the `libflutter_engine.so` parts are still unresolved.
Unfortunately, I haven't found any way to resolve __all__ symbols from this `.so`.

I have tried increasing `symbol_level` of profile builds to the same as debug builds: https://github.com/pwasowski2/buildroot/commit/8f6a8a5755cb711d3551eb504b698c59852f7a8e, but it didn't help to resolve more symbols.

**`enable_profiling = true`, `symbol_level = 2`**
<img width="960" alt="linux_profile_arm_enable_profiling_uncommented_symbols_set_2" src="https://user-images.githubusercontent.com/38784511/120475950-4f773080-c3aa-11eb-8a34-9bb85fc8ea4b.PNG">

In case, you're wondering, if setting gcc's `-g3` flag would enable resolution of all the symbols - the answer is _no_, as you can see in the last screenshot:

**`enable_profiling = true`, `symbol_level = 2`, `-g3` gcc flag**
<img width="960" alt="linux_profile_arm_enable_profiling_uncommented_symbols_set_2_gcc_g3_level" src="https://user-images.githubusercontent.com/38784511/120476064-73d30d00-c3aa-11eb-855f-bac2360968ed.PNG">


I think we can safely apply this https://github.com/pwasowski2/engine/commit/b9b44b9ad8b35f58c10e674be68282d42b73024d# to get almost all symbols, without setting `--unoptimized` or any other flag.

@swift-kim, @bbrto21 what do you think about it?

**Comment by swift-kim** [comment]
Thank you for the detailed analysis! The suggested change looks good to me, and I have a few quick questions:

- Are the remaining unresolved symbols related to text rendering? If so, could you check again by deleting the 271st line of the `shell/platform/embedder/BUILD.gn` file and rebuilding the engine? The version script file `flutter_engine_exports.lst` is supplied to `libflutter_engine.so` to prevent libfreetype symbols from being exported (#85).
- Did you try enabling the `enable_full_stack_frames_for_profiling` option which is defined along with `enable_profiling` in `build/config/profiler.gni`?

And some doubts:

- Would enabling `enable_profiling` cause any noticeable performance degradation? It seems they (Google) disabled it because it affected their benchmarks.
- ~Would enabling `enable_profiling` cause any issue on x86 emulator? It seems they (Google) had an issue related to unexpected text relocations on Android x86 by enabling the option, but this shouldn't be a problem on Tizen I think.~

**Comment by bbrto21** [comment]
> I have tried increasing symbol_level of profile builds to the same as debug builds: pwasowski2/buildroot@8f6a8a5, but it didn't help to resolve more symbols.

>In case, you're wondering, if setting gcc's -g3 flag would enable resolution of all the symbols - the answer is no, as you can see in the last screenshot:


The last time I tried to use symbol_level, it only worked as expected with "//build/config:debug". of course, there is a slight performance penalty.
@pwasowski2  Could you check the below?
```bash
diff --git a/build/config/BUILDCONFIG.gn b/build/config/BUILDCONFIG.gn
index 44c276c..70169f8 100644
--- a/build/config/BUILDCONFIG.gn
+++ b/build/config/BUILDCONFIG.gn
@@ -5,6 +5,9 @@
 # define is_wasm
 import("//build/toolchain/wasm.gni")
 
+# define enable_profiling
+import("//build/config/profiler.gni")
+
 # =============================================================================
 # PLATFORM SELECTION
 # =============================================================================
@@ -369,7 +372,10 @@ if (is_clang) {
 }
 
 # Optimizations and debug checking.
-if (is_debug) {
+if (enable_profiling) {
+  _native_compiler_configs += [ "//build/config:debug" ]
+  _default_optimization_config = "//build/config/compiler:optimize"
+} else if (is_debug) {
   _native_compiler_configs += [ "//build/config:debug" ]
   _default_optimization_config = "//build/config/compiler:no_optimize"
 } else {
@@ -382,7 +388,7 @@ _native_compiler_configs += [ _default_optimization_config ]
 if (symbol_level == -1) {
   # Linux is slowed by having symbols as part of the target binary, whereas
   # Mac and Windows have them separate, so in Release Linux, default them off.
-  if (is_debug || !is_linux) {
+  if (is_debug || !is_linux || enable_profiling) {
     symbol_level = 2
   } else if (is_asan || is_lsan || is_tsan || is_msan) {
     # Sanitizers require symbols for filename suppressions to work.
```
- config:debug : https://github.com/flutter/buildroot/blob/ff1975def53bfdaa1ff3f4b0cceabf54e1323392/build/config/BUILD.gn#L66
- config:complier:optimize : https://github.com/flutter/buildroot/blob/ff1975def53bfdaa1ff3f4b0cceabf54e1323392/build/config/compiler/BUILD.gn#L888

**Comment by pwasowski2** [comment]
Thanks for feedback, I have tested proposed build configuration changes and here's what I've found:

> Are the remaining unresolved symbols related to text rendering? If so, could you check again by deleting the 271st line of the shell/platform/embedder/BUILD.gn file and rebuilding the engine? The version script file flutter_engine_exports.lst is supplied to libflutter_engine.so to prevent libfreetype symbols from being exported (#85).

It seems, the unresolved symbols don't come from Freetype. After removeing the `ldflags = [ "-Wl,--version-script=" + rebase_path("flutter_engine_exports.lst") ]` from `shell/platform/embedder/BUILD.gn`, some symbols are still unresolved.

**`enable_profiling = true`, 271st line of the shell/platform/embedder/BUILD.gn commented out**
<img width="960" alt="linux_profile_arm_enable_profiling_uncommented_freetype_symbols_on" src="https://user-images.githubusercontent.com/38784511/120802658-fc84b100-c542-11eb-8839-5c54f3fd8a5e.PNG">

> Did you try enabling the enable_full_stack_frames_for_profiling option which is defined along with enable_profiling in build/config/profiler.gni?

Yes, I have and unfortunately, it didn't help, too.

**`enable_profiling = true`, `enable_full_stack_frames_for_profiling` enabled**
<img width="960" alt="linux_profile_arm_enable_profiling_uncommented_enable_full_stack_frames_for_profiling" src="https://user-images.githubusercontent.com/38784511/120802998-5b4a2a80-c543-11eb-80d0-36d2ac221f0b.PNG">

> The last time I tried to use symbol_level, it only worked as expected with "//build/config:debug". of course, there is a slight performance penalty.
> @pwasowski2 Could you check the below?

I have applied the diff to my repo and some symbols were still unresolved. When I have tested `symbols_level = 2` before, it was properly set by the compiler even without this change in `build/config/BUILDCONFIG.gn b/build/config/BUILDCONFIG.gn`:

```gn
 # Optimizations and debug checking.
-if (is_debug) {
+if (enable_profiling) {
+  _native_compiler_configs += [ "//build/config:debug" ]
+  _default_optimization_config = "//build/config/compiler:optimize"
+} else if (is_debug) {
```

**Comment by pwasowski2** [comment]
One more benchmark, that was missing in my previous comment:

**`profile` build with `--unoptimized`**
<img width="785" alt="linux_profile_arm_enable_profiling_commented_out_profile_unoptimized_build" src="https://user-images.githubusercontent.com/38784511/121000417-79ee3280-c78a-11eb-9ee6-d5241deac9d8.PNG">

Adding `--unoptimized` flag to `--profile` build seems to decrease the performance when compared to `--profile` with `--enable_profiling` enabled, but only slightly. With both these settings, the same amount of symbols is resolved.

@swift-kim, @bbrto21, I have made this PR ready for review https://github.com/flutter-tizen/engine/pull/104. Could you please take a look at it? :)
If we merge this PR, I think, we no longer need to add add information about enabling resolution of more symbols via `--unoptimized` `gn` flag to wiki - the same amount of symbols will be resolved by default in all `profile` builds.

**Comment by bbrto21** [comment]
Looks good!, I think this issue is almost closed now.
